### ISSUE TITLE
Rename chaos.h to cbridge.h

### ISSUE THREAD

**Issue by ams** [bictorv/chaosnet-bridge#2]
Would it be possible to rename the header to cbridge.h?

The background is that it kinda causes conflicts if you mix and match a bit with Chaosnet for Unix. :-)  I was thinking that maybe one should use chncp.h / chaos.h but those are quite gnarly to the simple header hear.

**Comment by bictorv** [comment]
But the content is not cbridge-specific, it's generic Chaos defs? Perhaps you could put your copy in a "cbridge/chaos.h" file, or something?

(Sorry, didn't see this until now.)

**Comment by ams** [comment]
Yeah, it is entirely unrelated to chaos-bridge.

It can’t really be merged either since it doesn’t contain any packet definitions, only some forward declarations to functions for opening/closing and IOCTL definitions.

I can send you the file if you want to see what is in it, the plan is to push this into the LM-3/chaos repo.

**Comment by bictorv** [comment]
What can't be merged? I still don't get it?

**Comment by ams** [comment]
The reason for the conflicts is that I install `chaos.h` (from _Chaosnet for Unix_) in `/usr/include`, and that will obviously cause a bit of headache.


The `chaos.h` file from _chaosnet-bridge_ and _Chaosnet for Unix_ can't be merged because they are two very different files.  The little in common they have is the packet opcode types.

For example, `struct chaosnet_packet` and `struct packet` (which doesn't live in `chaos.h` but rather in `chncp/chncp.h` in _Chaosnet for Unix_, which also doesn't get installed in `/usr/include`) are different structures and would require a decent amount of work to make both code bases use the same.  This is what the packets look like in _Chaosnet for Unix_ (it is more or less the same thing that _usim/chaosd_ uses):

```C
struct	pkt_header	{
	unsigned char		ph_type;	/* Protocol type */
	unsigned char		ph_op;		/* Opcode of the packet */
	chpklenfc		ph_lenfc;
  
	chaddr		ph_daddr;		/* Destination address */
	chindex		ph_didx;		/* Destination index */
	chaddr		ph_saddr;		/* Source address */
	chindex		ph_sidx;		/* Source index */
	unsigned short	LE_ph_pkn;			/* Packet number */
	unsigned short	LE_ph_ackn;		/* Acknowledged packet number */
};
/* This is the actual structure of a packet in core */
struct	packet	{
	struct ncp_header	pk_nhead;	/* NCP specific information */
	struct pkt_header	pk_phead;	/* Network header */
	union	{
		char 		pk_Cdata[sizeof(short)];/* Character data */
		short		pk_Idata[1];	/* word data */
		long		pk_Ldata[1];	/* long data */
		struct sts_data {		/* data of STS packets */
			unsigned short	LE_pk_Receipt;
			unsigned short	LE_pk_Rwsize;
		}		pk_stsdata;
		struct rut_data {		/* data of RUT packets */
			unsigned short	LE_pk_subnet;
			unsigned short	LE_pk_cost;
		}		pk_Rutdata[1];
		struct status	{ /* JAO: ANS packet for STATUS protocol? */
			char	sb_name[CHSTATNAME];
			struct	statdata {
				struct stathead {
					unsigned short	LE_sb_Ident;
					unsigned short	LE_sb_Nshorts;
				}		sb_head;
				union {
					struct statxcvr {
						long	LELNG_sx_Rcvd;
						long	LELNG_sx_Xmtd;
						long	LELNG_sx_Abrt;
						long	LELNG_sx_Lost;
						long	LELNG_sx_Crcr;
						long	LELNG_sx_Crci;
						long	LELNG_sx_Leng;
						long	LELNG_sx_Rej;
					}		sb_Xstat;
				}			sb_union;
			}				sb_data[1];
		}		pk_Status;
	}			pk_data;
};
```

**Comment by ams** [comment]
Here are the “original” files from Chaosnet for Unix:  https://github.com/LM-3/chaos/tree/ams/next

**Comment by bictorv** [comment]
OK, fixed, finally.

**Comment by ams** [comment]
Thank you!
