### ISSUE TITLE
Trouble building on Ubuntu 18

### ISSUE THREAD

**Issue by larsbrinkhoff** [bictorv/chaosnet-bridge#42]
Details to be posted here.

**Comment by larsbrinkhoff** [comment]
lsb_release -a

```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
```

**Comment by larsbrinkhoff** [comment]
Built latest master as of today, commit 3e116cf11cc0be8ab8448004197863a73641a92b.

Messages building chtls.c
```
cc -c -g -Wall -o chtls.o chtls.c
chtls.c: In function â:
chtls.c:397:7: warning: implicit declaration of function â; did you mean â? [-Wimplicit-function-declaration]
       X509_STORE_set_get_issuer(store, X509_STORE_CTX_get1_issuer);
       ^~~~~~~~~~~~~~~~~~~~~~~~~
       X509_STORE_CTX_get1_issuer
chtls.c: In function â:
chtls.c:1371:32: warning: implicit declaration of function â; did you mean â? [-Wimplicit-function-declaration]
  const ASN1_INTEGER *serialp = X509_get0_serialNumber(ssl_client_cert);
                                ^~~~~~~~~~~~~~~~~~~~~~
                                X509_get_serialNumber
chtls.c:1371:32: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
chtls.c: In function â:
chtls.c:1689:30: warning: implicit declaration of function â; did you mean â? [-Wimplicit-function-declaration]
   const ASN1_TIME *nupdate = X509_CRL_get0_nextUpdate(crl);
                              ^~~~~~~~~~~~~~~~~~~~~~~~
                              X509_CRL_get_nextUpdate
chtls.c:1689:30: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
chtls.c: In function â:
chtls.c:1818:31: warning: implicit declaration of function â; did you mean â? [-Wimplicit-function-declaration]
   const ASN1_TIME *notAfter = X509_get0_notAfter(cert);
                               ^~~~~~~~~~~~~~~~~~
                               X509_get_notAfter
chtls.c:1818:31: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
```

**Comment by bictorv** [comment]
Sorry, didn't see this until now. Can you please include your openssl version? `openssl version` should tell you.

The man page for `X509_get0_serialNumber` says

> The X509_get0_serialNumber() function was added in OpenSSL 1.1.0.

so you may be running some rather old version of openssl, which you should try to upgrade anyway, if possible? Could you check if it *is* possible/feasible?

Compiling doesn't complain about any missing include files, right?

**Comment by larsbrinkhoff** [comment]
```
OpenSSL 1.1.1  11 Sep 2018
```

No, no missing include files.

This is a remote VPS server.  I don't access the console very often, so rebooting, much less upgrading, is a bit of a risk.  With an uptime of 1607 days I suppose it's due for a restart so I should look into that.

**Comment by bictorv** [comment]
Mysterious. Could it be that you have a more recent openssl binary than dev package?

**Comment by larsbrinkhoff** [comment]
Maybe a reboot will help.  I'll try that soon...ish.

**Comment by bictorv** [comment]
Did you reboot yet? :-)

**Comment by larsbrinkhoff** [comment]
No.  I tend put it off as long as possible, and then some more.

**Comment by larsbrinkhoff** [comment]
Rebooted and upgraded to Ubuntu 20.  The latest cbridge version from master builds and runs fine.  As for the topic of this issue, building on Ubuntu 18, I suppose we can drop it.

**Comment by eswenson1** [comment]
Yeah, people running Ubuntu 18 deserved not to be able to build cbridge!

**Comment by bictorv** [comment]
> Rebooted and upgraded to Ubuntu 20. The latest cbridge version from master builds and runs fine. As for the topic of this issue, building on Ubuntu 18, I suppose we can drop it.

Good to hear!
