### ISSUE TITLE
Systemd scripts for cbridge?

### ISSUE THREAD

**Issue by ams** [bictorv/chaosnet-bridge#8]
I wrote two systemd scripts for handling cbridge and chaosd; is this of any interest to be merged?  The location of the files should probably be settled first, right now it assumes /home/ams/lm-3/...

**Comment by bictorv** [comment]
Sorry, didn't see this until now: yes, the cbridge script would be nice!

**Comment by ams** [comment]
I'll create a PR, but I'm wondering how to specify the location of cbridge in these scripts without hard coding it, and doing nasties with sed and @PREFIX@ tags.

https://github.com/ams/chaosnet-bridge/blob/8fef75f1ebe205668b929a97a67709db8e746872/cbridge.service

**Comment by bictorv** [comment]
Prossibly doing @Prefix@ tags and sed in the Makefile, using a variable in the makefile, would "work"?

**Comment by ams** [comment]
Yeah, I'll try to do this some day soon.  Busy with other stuff which is higher on my priority list.

**Comment by bictorv** [comment]
Wasn't this (at least partially) solved by https://github.com/bictorv/chaosnet-bridge/commit/a5aa8868b4e0947ff36760dd67966872efb46988 ?
Of course, when the automakification is in place, the path should be configurable.

**Comment by ams** [comment]
I guess so! Closing.
